language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "n6xWuyAdZE+uLJwh0QBfJgq3Aj8tTPZb1Yxc137y+kVQ8b3CRJp+F7GIFVmr2eKkoFVv9OsOv7uDIE6kQBfQKsE3QgN9zFIn9/jqiQfT4br8QEfh+xo3bwLSLxOs10zjMJ1+kp+pNXjFHEHYDI5BNgDTksZoFxjXOYFOv/z+8rK9HS2p9IK5xDhlZQ/AvxPOaL0zBpwcUSegxjMafFu7Y6zOO9AHgNFZY9VvuZPefM1LWPgQ6pLh5MTSYhDMdS37qTcSjHpEpVkb6tRTCsGDHCmcTOBmbg6G/wHSYiKzEQQ07D5Wt3RwbXZ0mb5dbXM8Mxs7GJE7X/CtsKbXVLdBogvGIrp7CmZH58f1fNAx0YryZqVIUFp+JOgWEP0Cwmy7OY/dqFcX6JWz+MnJlUrDWEoxfPZiiflTs7nMjq7g44nUx6/yjh3/V7Lk+UVmWS3OdWSQSlkD9LvPGMWnQxHfz22EOSHMdruKuyevB0KJcDQQtek38MLPCE88vCtzEjOTBm6PBDqWvt/p3LuO+bsbZ/Jn0EA1yz157V5to7fjdUR2ZhsnVLryk39QPGmSUOvdFkjDJ6w0PPCa8S0Kktz7jETis84e6uhpJ7vX9sTo/ifTeur3jVxDZDruOw0HBL1A658g9WNPLo9DyhkxTzOp36JPqE5Y422IN1I7oeGTb7Y="
